_base_: ["../base.yaml"]

task:
  name: "mrpc"
  dataset_name: "glue"
  dataset_config: "mrpc"
  
  # 数据字段映射（需要两个文本字段）
  text_fields: ["sentence1", "sentence2"]
  label_field: "label"
  
  # 评估指标配置
  metrics: ["accuracy", "f1"]
  evaluation_mode: "classification"
  
  # 模型输出配置
  num_labels: 2
  output_mode: "classification" 