_base_: ["../base.yaml"]

task:
  name: "qqp"
  dataset_name: "glue"
  dataset_config: "qqp"
  
  # 数据字段映射（问题对）
  text_fields: ["question1", "question2"]
  label_field: "label"
  
  # 评估指标配置
  metrics: ["accuracy", "f1"]
  evaluation_mode: "classification"
  
  # 模型输出配置
  num_labels: 2
  output_mode: "classification" 