_base_: ["../base.yaml"]

task:
  name: "rte"
  dataset_name: "glue"
  dataset_config: "rte"
  
  # 数据字段映射（前提-假设对）
  text_fields: ["sentence1", "sentence2"]
  label_field: "label"
  
  # 评估指标配置
  metrics: ["accuracy"]
  evaluation_mode: "classification"
  
  # 模型输出配置
  num_labels: 2
  output_mode: "classification" 